# Generated by Django 2.2.13 on 2020-09-08 21:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 21, 18, 9, 441669))),
                ('comment_likes', models.ManyToManyField(null=True, related_name='likes_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PReplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('reply_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 21, 18, 9, 443297))),
                ('reply_commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_commentor', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('reply_likes', models.ManyToManyField(null=True, related_name='comment_likes_post', to=settings.AUTH_USER_MODEL)),
                ('reply_to_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_to_comment', to='posts.PComments')),
            ],
        ),
        migrations.CreateModel(
            name='PPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=5000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='\\media')),
                ('post_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 21, 18, 9, 439987))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('post_likes', models.ManyToManyField(blank=True, null=True, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pcomments',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='posts.PPosts'),
        ),
        migrations.AddField(
            model_name='pcomments',
            name='commentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentor', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
