# Generated by Django 2.2.13 on 2020-09-09 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcomments',
            name='comment_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 9, 8, 16, 32, 392250)),
        ),
        migrations.AlterField(
            model_name='pposts',
            name='post_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 9, 8, 16, 32, 391059)),
        ),
        migrations.AlterField(
            model_name='preplycomment',
            name='reply_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 9, 8, 16, 32, 393580)),
        ),
    ]
