# Generated by Django 2.2.16 on 2020-10-06 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200909_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcomments',
            name='comment_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 6, 12, 10, 23, 766941)),
        ),
        migrations.AlterField(
            model_name='pposts',
            name='post_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 6, 12, 10, 23, 764683)),
        ),
        migrations.AlterField(
            model_name='preplycomment',
            name='reply_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 6, 12, 10, 23, 767884)),
        ),
    ]
